CREATE DATABASE Forensix
USE DATABASE Forensix

CREATE USER 'Forensix'@'%' IDENTIFIED VIA mysql_native_password USING '***';GRANT USAGE ON *.* TO 'Forensix'@'%' REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
GRANT ALL PRIVILEGES ON `forensix`.* TO 'Forensix'@'%' WITH GRANT OPTION;