CREATE DATABASE Forensix;

CREATE USER 'Forensix'@'%' IDENTIFIED VIA mysql_native_password USING PASSWORD('Forensix@123');
GRANT USAGE ON *.* TO 'Forensix'@'%' REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
GRANT ALL PRIVILEGES ON `forensix`.* TO 'Forensix'@'%' WITH GRANT OPTION;

USE Forensix;

CREATE TABLE IF NOT EXISTS CRIME_CASES(
    CASE_ID VARCHAR(32) NOT NULL PRIMARY KEY,
    TITLE VARCHAR(50) NOT NULL,
    DESCRIPTION VARCHAR(255) NOT NULL,
    TYPE VARCHAR(20) NOT NULL,
    STATUS INT NOT NULL,
    SEVERITY INT NOT NULL,
    LOCATION VARCHAR(255) NOT NULL,
    DATE_OCCURED DATETIME NOT NULL,
    DATE_REPORTED DATETIME NOT NULL,
    ASSIGNED_OFFICER VARCHAR(32),
    WITNESSES INT,
    NOTES VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS EVIDENCES(
    CASE_ID VARCHAR(32) NOT NULL REFERENCES CRIME_CASES(CASE_ID),
    TITLE VARCHAR(50) NOT NULL,
    REFERENCE VARCHAR(512) NOT NULL
);

DROP TABLE IF EXISTS MESSAGES;
DROP TABLE IF EXISTS CALL_LOGS;
DROP TABLE IF EXISTS CONTACTS;
DROP TABLE IF EXISTS FILES;

CREATE TABLE IF NOT EXISTS MESSAGES(
    ADDRESS VARCHAR(100) NOT NULL,
    BODY VARCHAR(512) NOT NULL,
    DATE_SENT DATETIME NOT NULL,
    DATE_RECEIVED DATETIME NOT NULL,
    TYPE VARCHAR(10) NOT NULL,
    SEEN VARCHAR(4) NOT NULL
);

CREATE TABLE IF NOT EXISTS CALL_LOGS(
    NUMBER VARCHAR(10) NOT NULL,
    DATE DATETIME NOT NULL,
    DURATION INT NOT NULL,
    TYPE VARCHAR(10) NOT NULL,
);

CREATE TABLE IF NOT EXISTS CONTACTS(
    NAME VARCHAR(50) NOT NULL,
    NUMBER VARCHAR(10) NOT NULL,
    GROUP INT NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
);

CREATE TABLE IF NOT EXISTS FILES(
    PATH VARCHAR(260) NOT NULL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    DIRECTORY VARCHAR(255) NOT NULL,
    SIZE INT NOT NULL,
    DATETIME DATETIME NOT NULL,
    EXT VARCHAR(5) NOT NULL
);